GET http://localhost:8000/v1/goals

###
GET http://localhost:8000/v1/goals/1

###
POST http://localhost:8000/v1/goals

{
    "name": "second goal",
    "priority": "high"
}

###
PUT http://localhost:8000/v1/goals/2

{
    "name": "second goal",
    "priority": "low"
}

###
DELETE http://localhost:8000/v1/goals/2

###