"""empty message

Revision ID: 0d77e8179283
Revises: 
Create Date: 2024-10-23 07:00:00.228711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d77e8179283'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('TO_REFINE', 'NOT_STARTED', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED', 'ABANDONED', name='goalstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='goalpriority'), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_due_date'), 'goal', ['due_date'], unique=False)
    op.create_index(op.f('ix_goal_name'), 'goal', ['name'], unique=False)
    op.create_index(op.f('ix_goal_priority'), 'goal', ['priority'], unique=False)
    op.create_index(op.f('ix_goal_status'), 'goal', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_status'), table_name='goal')
    op.drop_index(op.f('ix_goal_priority'), table_name='goal')
    op.drop_index(op.f('ix_goal_name'), table_name='goal')
    op.drop_index(op.f('ix_goal_due_date'), table_name='goal')
    op.drop_table('goal')
    # ### end Alembic commands ###
